max_epochs: 2
accelerator: "auto"
devices: "auto"
deterministic: False
log_every_n_steps: 1
gradient_clip_algorithm: "norm"
gradient_clip_val: 0
fast_dev_run: False
overfit_batches: 0.0
accumulate_grad_batches: 1
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
